###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{}
###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "id":1,
    "name":"victoria",
    "edad":"18",
    "telefono":"12434332422423432",
    "educacion":"secundaria",
    "estadoCivil":"casada",
    "genero":"femenino"
}
###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/2 HTTP/1.1

###
PUT http://localhost:9000/api/users/2 HTTP/1.1
Content-Type: application/json

{
    "id":2,
    "name":"victorias",
    "edad":"26",
    "telefono":"12434332422423432",
    "educacion":"secundaria",
    "estadoCivil":"casada",
    "genero":"femenino"
}
###
DELETE  http://localhost:9000/api/users/2 HTTP/1.1

### request juego###################################################juego#
###
POST http://localhost:9000/api/juegos HTTP/1.1
Content-Type: application/json

{}
###
POST http://localhost:9000/api/juegos HTTP/1.1
Content-Type: application/json

{
    "id":3,
    "tipo":28,
    "user":{
        "id":2,
        "name":"victoria",
        "edad":"26",
        "telefono":"12434332422423432",
        "educacion":"secundaria",
        "estadoCivil":"casada",
        "genero":"femenino"       
        },
    "posiciones":["casa","panaderia","oficina"],
    "posicionesTiempo":[1,2,3],
    "posicionesNumericas":[1,2,3,4]
}
###
GET http://localhost:9000/api/juegos HTTP/1.1

###
GET http://localhost:9000/api/juegos/2 HTTP/1.1

###
PUT http://localhost:9000/api/juegos/2 HTTP/1.1
Content-Type: application/json

{
    "id":2,
    "tipo":28,
    "user":{
        "id":2,
        "name":"victoriassss",
        "edad":"26",
        "telefono":"12434332422423432",
        "educacion":"secundaria",
        "estadoCivil":"casada",
        "genero":"femenino"       
        },
    "posiciones":[],
    "posicionesTiempo":[],
    "posicionesNumericas":[]
}
###
DELETE  http://localhost:9000/api/juegos/2 HTTP/1.1
